[workspace]
members = [
  "crates/fastrace",
  "crates/fastrace-macro",
  "crates/fastrace-opentelemetry",
  "crates/fastrace-futures",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/fast/fastrace"
rust-version = "1.91.0"

[workspace.dependencies]
# Workspace dependencies
fastrace = { version = "0.7.18", path = "crates/fastrace" }
fastrace-macro = { version = "0.7.18", path = "crates/fastrace-macro" }

# Workspace leaves
fastrace-futures = { path = "crates/fastrace-futures" }
fastrace-opentelemetry = { path = "crates/fastrace-opentelemetry" }

# crates.io dependencies
log = { version = "0.4.32" }
opentelemetry = { version = "0.32.0", default-features = false, features = [
  "trace",
] }
opentelemetry-otlp = { version = "0.32.0", default-features = false, features = [
  "trace",
  "grpc-tonic",
] }
opentelemetry_sdk = { version = "0.32.1", default-features = false, features = [
  "trace",
] }
serde = { version = "1.0.228", features = ["derive"] }

# test dependencies
tokio = { version = "1.52.3", features = ["full"] }
