comment_width = 120
edition = "2021"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
normalize_comments = true
overflow_delimited_expr = true
reorder_imports = true
style_edition = "2024"
trailing_comma = "Vertical"
where_single_line = true
wrap_comments = true
