[package]
name = "test-statically-disable"
publish = false
version = "0.0.0"

edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fastrace = { workspace = true }
